### PR TITLE
Add ESP32-C3-WROOM02(U)

### PR DESCRIPTION
**Pull request by dbrgn**
##### SUMMARY

This is one of the most popular versions of ESP32-C3 modules by Espressif.

There are two variants: The one without "U" has an on-board PCB antenna, while the variant with the "U" has an external antenna connector instead.

Symbol:

screenshot-20221230-220243

Packages:

screenshot-20221230-221736

##### DATASHEETS / REFERENCES

- [Digikey](https://www.digikey.ch/de/products/detail/espressif-systems/ESP32-C3-WROOM-02-N4/14553031)
- [Datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-c3-wroom-02_datasheet_en.pdf)
  - Pinout on page 10
  - Physical dimensions on page 26
  - Recommended land pattern on page 27

##### OPEN QUESTIONS / UNRESOLVED ISSUES

- The "{{NAME}}" placeholder above the antenna doesn't make much sense (since a cutout at the board edge for the antenna is recommended), but if we align name/value at the bottom left/right, then the texts will overlap 😕 I think the current approach is still best, although the user must manually move the name in most cases.
- Layouting notes on the "comments" layer: yay or nay?

##### CHECKLIST

- [x] I have read and followed the library conventions¹.
- [x] For packages, I followed IPC7351C (see details in library conventions).
- [x] For modified elements, I bumped their version number².
- [ ] I already used the new library elements in a design and verified their correctness (optional).
- [x] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x] I agree to publish all my changes under the CC0 Public Domain License³, allowing everyone to use and modify the content without any restrictions.

¹ *Library Conventions: https://docs.librepcb.org/#libraryconventions*
² *Minor version bump if only metadata was modified (e.g. "0.1" -> "0.1.1"), major version bump if functional changes were made (e.g. "0.1" -> "0.2")*
³ *CC0 Public Domain License: https://en.wikipedia.org/wiki/CC0*

### CODE REVIEW

**Comment by ubruhin** [comment]
Nice! Symbol and component look good to me :+1: Although I'm unsure about the separate `GND_EPAD` signal - the guidelines say there should be only one signal if they are connected in the package. With separate signals, the schematic defines whether it needs to be connected or not (it's more explicit, what I like). With merged signals, it's up to the board designer to connect one or both of the GND pads. Not sure which variant is better :thinking: 

Some notes:
- In the package without antenna, placement/documentation polygons overlap: 
  image
- Maybe moving the origin of the package with onboard antenna to the same location as for the package without antenna? I know the guidelines say it should be in the center of the body, but in this case it would allow switching between these two packages in a board without leading to an offset of all pads (and it's still not far away of the body center). However, I'm also fine with keeping it as-is, it's just an idea.
- For the devices I think  the `-N4` resp. `-H4` should be included in the name since these are actually different parts.

Regarding your questions: Where did you actually read there should be a board cutout? I can only see the note "keepout zone" in the datasheet, which is a different thing (no copper, no other devices). We don't support copper keepout zones yet, but for device keepout you could add a courtyard polygon. 

Btw I think in this case I'm fine with a short comment on the comments layer.

**Comment by dbrgn** [comment]
> With merged signals, it's up to the board designer to connect one or both of the GND pads. Not sure which variant is better thinking

I kept it separate because the datasheet explicitly mentions somewhere that soldering these pads is recommended, but optional.

> In the package without antenna, placement/documentation polygons overlap:

Oh, that's a mistake. Thanks for spotting!

> Maybe moving the origin of the package with onboard antenna to the same location as for the package without antenna? I know the guidelines say it should be in the center of the body, but in this case it would allow switching between these two packages in a board without leading to an offset of all pads (and it's still not far away of the body center). However, I'm also fine with keeping it as-is, it's just an idea.

I thought about that as well. I'd prefer that option, and only moved the origin because the guidelines say so 🙂 I'll move it back, so that the footprint doesn't move when switching the package.

> For the devices I think the -N4 resp. -H4 should be included in the name since these are actually different parts.

True!

> Regarding your questions: Where did you actually read there should be a board cutout? I can only see the note "keepout zone" in the datasheet, which is a different thing (no copper, no other devices).

Ah, that's not in the datasheet (only the keepout zone), but I noticed that many of the devboards have a cutout. I can change the wording if you have a good suggestion.

And I'll also add a courtyard, forgot about that.

**Comment by ubruhin** [comment]
> Ah, that's not in the datasheet (only the keepout zone), but I noticed that many of the devboards have a cutout. I can change the wording if you have a good suggestion.

OK in this case I'd only mention the keepout in the comment, not cutout since that's not an official recommendation. Maybe something like "Note: Keep area below antenna clear of copper"? Once LibrePCB supports keepout zones, the comment can even be removed. It would also be fine for me to remove the comment even now.

**Comment by dbrgn** [comment]
@ubruhin I think all issues are now addressed.

As for the courtyard, I used 0.2mm in general and 0.4mm around the antenna area for a slightly larger clearance.

**Review by ubruhin — APPROVED** [review]
Thanks, looks good to me! :rocket:

**Pull request merged**
